# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"  # See documentation for possible values
    directory: "tree/ghanmx-patch-1/docs/.github" # Location of package manifests
    schedule:
      interval: "weekly"


# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "tree/ghanmx-patch-1/docs/.github"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "tree/ghanmx-patch-1/docs/.github"
    schedule:
      interval: "daily"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "tree/ghanmx-patch-1/docs/.github"
    schedule:
      interval: "daily"
      
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "beta-ecosystem"
    directory: "#"
    schedule:
      interval: "daily"
      
- name: Cleanup code
  uses: Somfic/cleanupcode-action@1.1.1

- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.0
r
